//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.nebby1999.nebula:InputActionGUIDCodeGenerator
//     version 1.0.0
//     from Assets/ElementalWard/Base/ElementalWardInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine.InputSystem;
namespace ElementalWard
{
    public class ElementalWardInputGuids
    {
        // Player
        public static readonly Guid PlayerGUID = Guid.Parse("838885bd-4351-4d2e-bd5f-f08ca3b76ef4");
        public class Player
        {
            public static readonly Guid MoveGUID = Guid.Parse("9dd093b7-369f-483d-a9a9-c50d637b6085");
            public static readonly Guid LookGUID = Guid.Parse("f765e2fe-57bb-4f7d-96f0-745b10c49fac");
            public static readonly Guid JumpGUID = Guid.Parse("bc938039-836b-4bc8-bc60-56b806693359");
            private Player() {}
        }
        // UI
        public static readonly Guid UIGUID = Guid.Parse("0a8dd952-d692-4a3b-ba01-658df73f0deb");
        public class UI
        {
            public static readonly Guid NavigateGUID = Guid.Parse("fc297492-70ae-4de4-aa21-27127716aacd");
            public static readonly Guid SubmitGUID = Guid.Parse("592c5845-d4ae-4364-ac3b-22503433f1a6");
            public static readonly Guid CancelGUID = Guid.Parse("204bff70-75f2-499e-8b89-172919e61a89");
            public static readonly Guid PointGUID = Guid.Parse("686e974b-8766-49a8-8e6b-161f82d7a61b");
            public static readonly Guid ClickGUID = Guid.Parse("ecb645bd-f3f5-4210-84c2-580cc507d553");
            public static readonly Guid ScrollWheelGUID = Guid.Parse("1b73225a-a01d-46a7-b8b3-5af9e9e4bd0d");
            public static readonly Guid MiddleClickGUID = Guid.Parse("be667adc-44ea-4017-8866-e23b229dd78b");
            public static readonly Guid RightClickGUID = Guid.Parse("214f23f9-6762-47d1-a38c-0826a3d1b538");
            public static readonly Guid TrackedDevicePositionGUID = Guid.Parse("f7a4713a-02fd-4d8e-a05e-6ad807e0c821");
            public static readonly Guid TrackedDeviceOrientationGUID = Guid.Parse("494c5cda-6ce7-45de-81e6-4e83583b833b");
            private UI() {}
        }
        private ElementalWardInputGuids() {}
    }
}
