//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.nebby1999.nebula:InputActionGUIDCodeGenerator
//     version 1.0.0
//     from Assets/ElementalWard/Base/Core/ElementalWardInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine.InputSystem;
namespace ElementalWard
{
    public class ElementalWardInputGuids
    {
        // Player
        public static readonly Guid playerGUID = Guid.Parse("838885bd-4351-4d2e-bd5f-f08ca3b76ef4");
        public class Player
        {
            public static readonly Guid moveGUID = Guid.Parse("9dd093b7-369f-483d-a9a9-c50d637b6085");
            public static readonly Guid lookGUID = Guid.Parse("f765e2fe-57bb-4f7d-96f0-745b10c49fac");
            public static readonly Guid jumpGUID = Guid.Parse("bc938039-836b-4bc8-bc60-56b806693359");
            public static readonly Guid sprintGUID = Guid.Parse("e4637507-4466-4625-bf18-5c38c76eed38");
            public static readonly Guid fireGUID = Guid.Parse("b6a69f30-2f02-407d-9e46-93a072e375ce");
            public static readonly Guid elementScrollGUID = Guid.Parse("90496791-75a5-486f-a739-1442f5dcf45d");
            private Player() {}
        }
        // UI
        public static readonly Guid uIGUID = Guid.Parse("0a8dd952-d692-4a3b-ba01-658df73f0deb");
        public class UI
        {
            public static readonly Guid navigateGUID = Guid.Parse("fc297492-70ae-4de4-aa21-27127716aacd");
            public static readonly Guid submitGUID = Guid.Parse("592c5845-d4ae-4364-ac3b-22503433f1a6");
            public static readonly Guid cancelGUID = Guid.Parse("204bff70-75f2-499e-8b89-172919e61a89");
            public static readonly Guid pointGUID = Guid.Parse("686e974b-8766-49a8-8e6b-161f82d7a61b");
            public static readonly Guid clickGUID = Guid.Parse("ecb645bd-f3f5-4210-84c2-580cc507d553");
            public static readonly Guid scrollWheelGUID = Guid.Parse("1b73225a-a01d-46a7-b8b3-5af9e9e4bd0d");
            public static readonly Guid middleClickGUID = Guid.Parse("be667adc-44ea-4017-8866-e23b229dd78b");
            public static readonly Guid rightClickGUID = Guid.Parse("214f23f9-6762-47d1-a38c-0826a3d1b538");
            public static readonly Guid trackedDevicePositionGUID = Guid.Parse("f7a4713a-02fd-4d8e-a05e-6ad807e0c821");
            public static readonly Guid trackedDeviceOrientationGUID = Guid.Parse("494c5cda-6ce7-45de-81e6-4e83583b833b");
            private UI() {}
        }
        private ElementalWardInputGuids() {}
    }
}
