//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.nebby1999.nebula:GameTagDataCodeGenerator
//     version 1.0.0
//     from Project Settings
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementalWard
{
    public static class GameTagscs
    {
        public static readonly string untagged = "Untagged";
        public static readonly string respawn = "Respawn";
        public static readonly string finish = "Finish";
        public static readonly string editorOnly = "EditorOnly";
        public static readonly string mainCamera = "MainCamera";
        public static readonly string player = "Player";
        public static readonly string gameController = "GameController";
    }
}
